#!/bin/bash
set -euo pipefail

# Convert Phosphor Icons SVGs to SF Symbol format using SwiftDraw
# Generates: raw SVGs, Xcode asset catalog, and type-safe Swift code
#
# Usage: ./Scripts/convert.sh [phosphor-core-path] [output-path]

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

PHOSPHOR_CORE="${1:-phosphor-core}"
OUTPUT_DIR="${2:-Symbols}"

XCASSETS_DIR="$ROOT_DIR/Sources/PhosphorSymbols/Resources/PhosphorSymbols.xcassets"
SWIFT_OUT="$ROOT_DIR/Sources/PhosphorSymbols/PhosphorSymbol+All.swift"

ASSETS_DIR="$PHOSPHOR_CORE/assets"

if [ ! -d "$ASSETS_DIR" ]; then
  echo "Error: Phosphor core assets not found at $ASSETS_DIR"
  echo "Run: git clone https://github.com/phosphor-icons/core.git $PHOSPHOR_CORE"
  exit 1
fi

if ! command -v swiftdraw &> /dev/null; then
  echo "Error: swiftdraw not found. Install with: brew install swiftdraw"
  exit 1
fi

# --- Conversion -----------------------------------------------------------

rm -rf "$OUTPUT_DIR" "$XCASSETS_DIR"
mkdir -p "$OUTPUT_DIR/outline" "$OUTPUT_DIR/fill"
mkdir -p "$XCASSETS_DIR"

# Root Contents.json for the asset catalog
cat > "$XCASSETS_DIR/Contents.json" << 'CATJSON'
{
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
CATJSON

TOTAL=0
FAILED=0

# Collect symbol names for Swift codegen
OUTLINE_NAMES=()
FILL_NAMES=()

# Helper: create a .symbolset inside the asset catalog
create_symbolset() {
  local symbol_name="$1"
  local svg_source="$2"
  local set_dir="$XCASSETS_DIR/${symbol_name}.symbolset"

  mkdir -p "$set_dir"
  cp "$svg_source" "$set_dir/${symbol_name}.svg"
  cat > "$set_dir/Contents.json" << SETJSON
{
  "info" : {
    "author" : "xcode",
    "version" : 1
  },
  "symbols" : [
    {
      "filename" : "${symbol_name}.svg",
      "idiom" : "universal"
    }
  ]
}
SETJSON
}

# Convert outline variants (regular + thin as ultralight + bold as black)
echo "Converting outline variants..."
for svg in "$ASSETS_DIR/regular/"*.svg; do
  name=$(basename "$svg" .svg)

  thin_svg="$ASSETS_DIR/thin/${name}.svg"
  bold_svg="$ASSETS_DIR/bold/${name}.svg"

  out_file="$OUTPUT_DIR/outline/${name}.svg"
  args=("$svg" --format sfsymbol --insets auto --output "$out_file")

  if [ -f "$thin_svg" ]; then
    args+=(--ultralight "$thin_svg")
  fi
  if [ -f "$bold_svg" ]; then
    args+=(--black "$bold_svg")
  fi

  if swiftdraw "${args[@]}" 2>/dev/null; then
    create_symbolset "$name" "$out_file"
    OUTLINE_NAMES+=("$name")
    ((TOTAL++))
  else
    echo "  Failed: $name"
    ((FAILED++))
  fi
done

# Convert fill variants
echo "Converting fill variants..."
for svg in "$ASSETS_DIR/fill/"*.svg; do
  name=$(basename "$svg" .svg)
  clean_name="${name%-fill}.fill"

  out_file="$OUTPUT_DIR/fill/${clean_name}.svg"
  if swiftdraw "$svg" --format sfsymbol --insets auto --output "$out_file" 2>/dev/null; then
    create_symbolset "$clean_name" "$out_file"
    FILL_NAMES+=("$clean_name")
    ((TOTAL++))
  else
    echo "  Failed: $clean_name"
    ((FAILED++))
  fi
done

# --- Swift Codegen ---------------------------------------------------------

echo "Generating Swift source..."

# Convert identifier to Swift property name:
# - hyphens become underscores
# - dots become underscores
to_swift_name() {
  local input="$1"
  echo "$input" | tr '-.' '__'
}

# Swift reserved keywords that need backtick escaping
is_swift_keyword() {
  local name="$1"
  case "$name" in
    as|break|case|catch|class|continue|default|defer|deinit|do|else|\
    enum|extension|fallthrough|false|fileprivate|for|func|guard|if|\
    import|in|init|inout|internal|is|let|nil|open|operator|override|\
    private|precedencegroup|protocol|public|repeat|rethrows|return|\
    self|Self|static|struct|subscript|super|switch|throw|throws|true|\
    try|typealias|var|where|while)
      return 0 ;;
    *)
      return 1 ;;
  esac
}

{
  cat << 'HEADER'
// This file is auto-generated by Scripts/convert.sh
// Do not edit manually.

import Foundation

extension PhosphorSymbol {
HEADER

  # Outline symbols
  for name in "${OUTLINE_NAMES[@]}"; do
    swift_name=$(to_swift_name "$name")
    if is_swift_keyword "$swift_name"; then
      echo "    static public let \`${swift_name}\` = PhosphorSymbol(identifier: \"${name}\")"
    else
      echo "    static public let ${swift_name} = PhosphorSymbol(identifier: \"${name}\")"
    fi
  done

  # Fill symbols
  for name in "${FILL_NAMES[@]}"; do
    swift_name=$(to_swift_name "$name")
    if is_swift_keyword "$swift_name"; then
      echo "    static public let \`${swift_name}\` = PhosphorSymbol(identifier: \"${name}\")"
    else
      echo "    static public let ${swift_name} = PhosphorSymbol(identifier: \"${name}\")"
    fi
  done

  echo "}"
} > "$SWIFT_OUT"

echo ""
echo "Done! Converted $TOTAL symbols ($FAILED failed)"
echo "  Raw SVGs:      $OUTPUT_DIR/"
echo "  Asset catalog: $XCASSETS_DIR"
echo "  Swift source:  $SWIFT_OUT"
